// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127140324_ActiveUserEffectAndShopItemRefactor")]
    partial class ActiveUserEffectAndShopItemRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResetPasswordCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordCodeExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasFilter("[Login] IS NOT NULL");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ActiveUserEffect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EffectType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SourceItemId")
                        .HasColumnType("int");

                    b.Property<int?>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EffectDataJson");

                    b.HasKey("Id");

                    b.HasIndex("SourceItemId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ActiveUserEffects", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Badges", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#008000",
                            Description = "One week of daily quests in a row!",
                            Text = "Daily Streak: 7",
                            Type = "CompleteDailySeven"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#008000",
                            Description = "A whole month of consistency. The fire never went out.",
                            Text = "Daily Streak: 30",
                            Type = "CompleteDailyThirty"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#008000",
                            Description = "Completed a monthly quest every month for a full year.",
                            Text = "Cycle Breaker",
                            Type = "CompleteMonthlyTwelve"
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#008000",
                            Description = "500 quests completed. Legendary endurance!",
                            Text = "Quest Master",
                            Type = "Complete500Quests"
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "#ffbf00",
                            Description = "You set your very first goal.",
                            Text = "Dreamer",
                            Type = "GoalCreateFirst"
                        },
                        new
                        {
                            Id = 6,
                            ColorHex = "#ffbf00",
                            Description = "You drafted 10 goals to challenge yourself.",
                            Text = "Planner",
                            Type = "GoalCreateTen"
                        },
                        new
                        {
                            Id = 7,
                            ColorHex = "#ffbf00",
                            Description = "Your first goal completed. The journey begins.",
                            Text = "Achiever",
                            Type = "GoalCompleteFirst"
                        },
                        new
                        {
                            Id = 8,
                            ColorHex = "#ffbf00",
                            Description = "10 goals done. Determination proven.",
                            Text = "Goal Getter",
                            Type = "GoalCompleteTen"
                        },
                        new
                        {
                            Id = 9,
                            ColorHex = "#ffbf00",
                            Description = "50 goals achieved. You’ve come a long way.",
                            Text = "Vision Realized",
                            Type = "GoalCompleteFifty"
                        },
                        new
                        {
                            Id = 10,
                            ColorHex = "#ffd700",
                            Description = "Completed a yearly goal. True perseverance.",
                            Text = "Yearly Champion",
                            Type = "GoalCompleteYearly"
                        },
                        new
                        {
                            Id = 11,
                            ColorHex = "#0000ff",
                            Description = "Your adventure begins with the very first quest.",
                            Text = "First Quest!",
                            Type = "CreateFirstQuest"
                        },
                        new
                        {
                            Id = 12,
                            ColorHex = "#0000ff",
                            Description = "Twenty quests written into your story.",
                            Text = "Quest Scribe",
                            Type = "CreateTwentyQuests"
                        },
                        new
                        {
                            Id = 13,
                            ColorHex = "#0000ff",
                            Description = "100 quests forged. A true architect of challenges.",
                            Text = "Quest Factory",
                            Type = "Create100Quests"
                        },
                        new
                        {
                            Id = 14,
                            ColorHex = "#6a0dad",
                            Description = "Your first companion on the journey.",
                            Text = "Ally Found",
                            Type = "MakeOneFriend"
                        },
                        new
                        {
                            Id = 15,
                            ColorHex = "#6a0dad",
                            Description = "Five allies joined your party.",
                            Text = "Band of Allies",
                            Type = "MakeFiveFriends"
                        },
                        new
                        {
                            Id = 16,
                            ColorHex = "#6a0dad",
                            Description = "Ten friends along the way.",
                            Text = "Social Starter",
                            Type = "MakeTenFriends"
                        },
                        new
                        {
                            Id = 17,
                            ColorHex = "#6a0dad",
                            Description = "Twenty friends — your guild thrives.",
                            Text = "Party Leader",
                            Type = "MakeTwentyFriends"
                        },
                        new
                        {
                            Id = 18,
                            ColorHex = "#ff0000",
                            Description = "Failed 10 times, but always rose again.",
                            Text = "Phoenix",
                            Type = "FailureComeback"
                        },
                        new
                        {
                            Id = 19,
                            ColorHex = "#ff0000",
                            Description = "Lost your streak, but started again. That’s true grit.",
                            Text = "Gritty Hero",
                            Type = "StreakRecovery"
                        },
                        new
                        {
                            Id = 20,
                            ColorHex = "#c0c0c0",
                            Description = "Completed 10 daily, 10 weekly, and 10 monthly quests.",
                            Text = "Balanced Hero",
                            Type = "BalancedHero"
                        });
                });

            modelBuilder.Entity("Domain.Models.FriendInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ReceiverUserProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderUserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverUserProfileId");

                    b.HasIndex("SenderUserProfileId", "ReceiverUserProfileId", "Status")
                        .IsUnique();

                    b.ToTable("FriendInvitations", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Friendship", b =>
                {
                    b.Property<int>("UserProfileId1")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId2")
                        .HasColumnType("int");

                    b.Property<DateTime>("BecameFriendsAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserProfileId1", "UserProfileId2");

                    b.HasIndex("UserProfileId2");

                    b.HasIndex("UserProfileId1", "UserProfileId2")
                        .IsUnique();

                    b.ToTable("Friendships", (string)null);
                });

            modelBuilder.Entity("Domain.Models.MonthlyQuest_Days", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndDay")
                        .HasColumnType("int");

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<int>("StartDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestId")
                        .IsUnique();

                    b.ToTable("MonthlyQuest_Days", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("Id", "UserProfileId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Emoji")
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextResetAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("QuestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("time");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("WasEverCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("QuestType");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserProfileId", "QuestType");

                    b.ToTable("Quests", (string)null);
                });

            modelBuilder.Entity("Domain.Models.QuestLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("Value");

                    b.ToTable("Quest_Labels", (string)null);
                });

            modelBuilder.Entity("Domain.Models.QuestOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurrenceEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurrenceStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<bool>("WasCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("OccurrenceStart");

                    b.HasIndex("QuestId");

                    b.HasIndex("QuestId", "OccurrenceStart", "OccurrenceEnd")
                        .IsUnique();

                    b.ToTable("QuestOccurrences", (string)null);
                });

            modelBuilder.Entity("Domain.Models.QuestStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompletionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LongestStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("OccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestId")
                        .IsUnique();

                    b.ToTable("QuestStatistics", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Quest_QuestLabel", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<int>("QuestLabelId")
                        .HasColumnType("int");

                    b.HasKey("QuestId", "QuestLabelId");

                    b.HasIndex("QuestLabelId");

                    b.ToTable("Quest_QuestLabel", (string)null);
                });

            modelBuilder.Entity("Domain.Models.SeasonalQuest_Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestId")
                        .IsUnique();

                    b.ToTable("SeasonalQuest_Seasons", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPurchasable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsUnique")
                        .HasColumnType("bit");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<int>("LevelRequirement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("ShopItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Category = 0,
                            CurrencyType = 0,
                            Description = "Unlocked at Level 1. Made from 100% imaginary wood.",
                            ImageUrl = "frames/wooden_rookie",
                            IsPurchasable = false,
                            IsUnique = true,
                            ItemType = 0,
                            LevelRequirement = 1,
                            Name = "Wooden Rookie Frame",
                            Payload = "{\"type\":\"AvatarFrame\",\"FrameId\":\"wooden_rookie\"}",
                            Price = 0
                        },
                        new
                        {
                            Id = 101,
                            Category = 0,
                            CurrencyType = 0,
                            Description = "Unlocked at Level 4. Clean, shiny, probably not real silver.",
                            ImageUrl = "frames/silver_striver",
                            IsPurchasable = false,
                            IsUnique = true,
                            ItemType = 0,
                            LevelRequirement = 4,
                            Name = "Silver Striver Frame",
                            Payload = "{\"type\":\"AvatarFrame\",\"FrameId\":\"silver_striver\"}",
                            Price = 0
                        },
                        new
                        {
                            Id = 102,
                            Category = 0,
                            CurrencyType = 0,
                            Description = "Unlocked at Level 8. You earned this—literally.",
                            ImageUrl = "frames/gold_grinder",
                            IsPurchasable = false,
                            IsUnique = true,
                            ItemType = 0,
                            LevelRequirement = 8,
                            Name = "Gold Grinder Frame",
                            Payload = "{\"type\":\"AvatarFrame\",\"FrameId\":\"gold_grinder\"}",
                            Price = 0
                        },
                        new
                        {
                            Id = 103,
                            Category = 0,
                            CurrencyType = 0,
                            Description = "Unlocked at Level 15. Shiny enough to motivate anyone.",
                            ImageUrl = "frames/diamond_achiever",
                            IsPurchasable = false,
                            IsUnique = true,
                            ItemType = 0,
                            LevelRequirement = 15,
                            Name = "Diamond Achiever Frame",
                            Payload = "{\"type\":\"AvatarFrame\",\"FrameId\":\"diamond_achiever\"}",
                            Price = 0
                        },
                        new
                        {
                            Id = 200,
                            Category = 1,
                            CurrencyType = 0,
                            Description = "A cat furiously typing on a keyboard. Appears to know more than you.",
                            ImageUrl = "avatars/cat_programmer",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 2,
                            LevelRequirement = 1,
                            Name = "Cat Programmer",
                            Payload = "{\"type\":\"Avatar\",\"AvatarId\":\"cat_programmer\"}",
                            Price = 300
                        },
                        new
                        {
                            Id = 201,
                            Category = 1,
                            CurrencyType = 0,
                            Description = "The peak of digital evolution. Jawline DLC included.",
                            ImageUrl = "avatars/giga_chad",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 2,
                            LevelRequirement = 5,
                            Name = "Giga-Chad Avatar",
                            Payload = "{\"type\":\"Avatar\",\"AvatarId\":\"giga_chad\"}",
                            Price = 400
                        },
                        new
                        {
                            Id = 202,
                            Category = 1,
                            CurrencyType = 0,
                            Description = "A stressed wizard constantly casting 'EXTEND DEADLINE' spell.",
                            ImageUrl = "avatars/wizard_deadlines",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 2,
                            LevelRequirement = 3,
                            Name = "Wizard of Deadlines",
                            Payload = "{\"type\":\"Avatar\",\"AvatarId\":\"wizard_deadlines\"}",
                            Price = 350
                        },
                        new
                        {
                            Id = 300,
                            Category = 5,
                            CurrencyType = 0,
                            Description = "A baby dragon that follows you around. Harmless. Probably.",
                            ImageUrl = "pets/tiny_dragon",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 5,
                            LevelRequirement = 10,
                            Name = "Tiny Dragon",
                            Payload = "{\"type\":\"Pet\",\"PetId\":\"tiny_dragon\",\"Animation\":\"hover\"}",
                            Price = 1200
                        },
                        new
                        {
                            Id = 301,
                            Category = 5,
                            CurrencyType = 0,
                            Description = "A yellow duck that defies gravity. Scientists hate it.",
                            ImageUrl = "pets/floating_duck",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 5,
                            LevelRequirement = 6,
                            Name = "Floating Duck",
                            Payload = "{\"type\":\"Pet\",\"PetId\":\"floating_duck\",\"Animation\":\"float\"}",
                            Price = 800
                        },
                        new
                        {
                            Id = 400,
                            Category = 6,
                            CurrencyType = 0,
                            Description = "A title that proudly states what everyone already knew.",
                            ImageUrl = "titles/procrastinator",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 6,
                            LevelRequirement = 1,
                            Name = "Certified Procrastinator",
                            Payload = "{\"type\":\"Title\",\"TitleText\":\"Certified Procrastinator\"}",
                            Price = 250
                        },
                        new
                        {
                            Id = 401,
                            Category = 6,
                            CurrencyType = 0,
                            Description = "For those who finish tasks with extreme prejudice.",
                            ImageUrl = "titles/slayer",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 6,
                            LevelRequirement = 8,
                            Name = "Task Slayer",
                            Payload = "{\"type\":\"Title\",\"TitleText\":\"Task Slayer\"}",
                            Price = 600
                        },
                        new
                        {
                            Id = 402,
                            Category = 6,
                            CurrencyType = 0,
                            Description = "One title to postpone them all.",
                            ImageUrl = "titles/lord_deadlines",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 6,
                            LevelRequirement = 12,
                            Name = "Lord of Deadlines",
                            Payload = "{\"type\":\"Title\",\"TitleText\":\"Lord of Deadlines\"}",
                            Price = 900
                        },
                        new
                        {
                            Id = 500,
                            Category = 3,
                            CurrencyType = 0,
                            Description = "Makes your username glow with neon blue energy.",
                            ImageUrl = "nameeffects/neon_blue",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 8,
                            LevelRequirement = 4,
                            Name = "Blue Neon Name Glow",
                            Payload = "{\"type\":\"NameEffect\",\"EffectStyle\":\"glow\",\"ColorHex\":\"#00AFFF\"}",
                            Price = 500
                        },
                        new
                        {
                            Id = 501,
                            Category = 3,
                            CurrencyType = 0,
                            Description = "Your username ignites with flame animation.",
                            ImageUrl = "nameeffects/inferno",
                            IsPurchasable = true,
                            IsUnique = true,
                            ItemType = 8,
                            LevelRequirement = 10,
                            Name = "Inferno Name Aura",
                            Payload = "{\"type\":\"NameEffect\",\"EffectStyle\":\"aura\",\"ColorHex\":\"#FF4500\"}",
                            Price = 950
                        },
                        new
                        {
                            Id = 600,
                            Category = 4,
                            CurrencyType = 0,
                            Description = "+40 XP on next completed task. Tastes digital.",
                            ImageUrl = "consumables/snack",
                            IsPurchasable = true,
                            IsUnique = false,
                            ItemType = 1,
                            LevelRequirement = 1,
                            Name = "Mini XP Snack",
                            Payload = "{\"type\":\"Consumable\",\"EffectType\":2,\"DurationMinutes\":null,\"UsageCount\":1,\"Multiplier\":null,\"FlatValue\":40}",
                            Price = 120
                        },
                        new
                        {
                            Id = 601,
                            Category = 4,
                            CurrencyType = 0,
                            Description = "+120 XP on next completed task.",
                            ImageUrl = "consumables/giga_meal",
                            IsPurchasable = true,
                            IsUnique = false,
                            ItemType = 1,
                            LevelRequirement = 6,
                            Name = "Giga XP Meal",
                            Payload = "{\"type\":\"Consumable\",\"EffectType\":2,\"DurationMinutes\":null,\"UsageCount\":1,\"Multiplier\":null,\"FlatValue\":120}",
                            Price = 450
                        },
                        new
                        {
                            Id = 602,
                            Category = 4,
                            CurrencyType = 0,
                            Description = "Doubles XP for the next 2 tasks.",
                            ImageUrl = "consumables/focus_brew",
                            IsPurchasable = true,
                            IsUnique = false,
                            ItemType = 1,
                            LevelRequirement = 10,
                            Name = "Ultra Focus Brew",
                            Payload = "{\"type\":\"Consumable\",\"EffectType\":0,\"DurationMinutes\":null,\"UsageCount\":2,\"Multiplier\":2,\"FlatValue\":null}",
                            Price = 800
                        });
                });

            modelBuilder.Entity("Domain.Models.UserBlock", b =>
                {
                    b.Property<int>("BlockerUserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("BlockedUserProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("BlockerUserProfileId", "BlockedUserProfileId");

                    b.HasIndex("BlockedUserProfileId");

                    b.HasIndex("BlockerUserProfileId", "BlockedUserProfileId")
                        .IsUnique();

                    b.ToTable("UserBlocks", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AchievedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoalType")
                        .HasColumnType("int");

                    b.Property<bool>("IsAchieved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("XpBonus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.HasKey("Id");

                    b.HasIndex("EndsAt");

                    b.HasIndex("QuestId");

                    b.HasIndex("UserProfileId", "IsAchieved", "IsExpired");

                    b.HasIndex("UserProfileId", "IsExpired", "QuestId");

                    b.ToTable("UserGoals", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcquiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ShopItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("UserProfileId", "ShopItemId")
                        .IsUnique();

                    b.ToTable("UserInventories", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("ActiveGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Coins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CompletedDailyQuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CompletedGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CompletedMonthlyQuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CompletedQuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CompletedWeeklyQuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CurrentlyCompletedExistingQuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EverCompletedExistingQuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ExistingQuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ExpiredGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FriendsCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Etc/UTC");

                    b.Property<int>("TotalGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalQuests")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Domain.Models.UserProfile_Badge", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("UserProfileId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserProfileId", "EarnedAt");

                    b.ToTable("UserProfile_Badges", (string)null);
                });

            modelBuilder.Entity("Domain.Models.WeeklyQuest_Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<int>("Weekday")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestId");

                    b.ToTable("WeeklyQuest_Days", (string)null);
                });

            modelBuilder.Entity("Domain.Models.ActiveUserEffect", b =>
                {
                    b.HasOne("Domain.Models.ShopItem", "SourceItem")
                        .WithMany("ActiveUserEffects")
                        .HasForeignKey("SourceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.UserProfile", "UserProfile")
                        .WithMany("ActiveUserEffects")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceItem");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Domain.Models.FriendInvitation", b =>
                {
                    b.HasOne("Domain.Models.UserProfile", "Receiver")
                        .WithMany("ReceivedFriendInvitations")
                        .HasForeignKey("ReceiverUserProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Models.UserProfile", "Sender")
                        .WithMany("SentFriendInvitations")
                        .HasForeignKey("SenderUserProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Models.Friendship", b =>
                {
                    b.HasOne("Domain.Models.UserProfile", "UserProfile1")
                        .WithMany("FriendshipsAsUser1")
                        .HasForeignKey("UserProfileId1")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Models.UserProfile", "UserProfile2")
                        .WithMany("FriendshipsAsUser2")
                        .HasForeignKey("UserProfileId2")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserProfile1");

                    b.Navigation("UserProfile2");
                });

            modelBuilder.Entity("Domain.Models.MonthlyQuest_Days", b =>
                {
                    b.HasOne("Domain.Models.Quest", "Quest")
                        .WithOne("MonthlyQuest_Days")
                        .HasForeignKey("Domain.Models.MonthlyQuest_Days", "QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Domain.Models.Notification", b =>
                {
                    b.HasOne("Domain.Models.UserProfile", "UserProfile")
                        .WithMany("Notifications")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Domain.Models.Quest", b =>
                {
                    b.HasOne("Domain.Models.UserProfile", "UserProfile")
                        .WithMany("Quests")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Domain.Models.QuestLabel", b =>
                {
                    b.HasOne("Domain.Models.UserProfile", "UserProfile")
                        .WithMany("Labels")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Domain.Models.QuestOccurrence", b =>
                {
                    b.HasOne("Domain.Models.Quest", "Quest")
                        .WithMany("QuestOccurrences")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Domain.Models.QuestStatistics", b =>
                {
                    b.HasOne("Domain.Models.Quest", "Quest")
                        .WithOne("Statistics")
                        .HasForeignKey("Domain.Models.QuestStatistics", "QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Domain.Models.Quest_QuestLabel", b =>
                {
                    b.HasOne("Domain.Models.Quest", "Quest")
                        .WithMany("Quest_QuestLabels")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.QuestLabel", "QuestLabel")
                        .WithMany("Quest_QuestLabels")
                        .HasForeignKey("QuestLabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("QuestLabel");
                });

            modelBuilder.Entity("Domain.Models.SeasonalQuest_Season", b =>
                {
                    b.HasOne("Domain.Models.Quest", "Quest")
                        .WithOne("SeasonalQuest_Season")
                        .HasForeignKey("Domain.Models.SeasonalQuest_Season", "QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Domain.Models.UserBlock", b =>
                {
                    b.HasOne("Domain.Models.UserProfile", "BlockedUserProfile")
                        .WithMany("ReceivedBlocks")
                        .HasForeignKey("BlockedUserProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Models.UserProfile", "BlockerUserProfile")
                        .WithMany("SentBlocks")
                        .HasForeignKey("BlockerUserProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BlockedUserProfile");

                    b.Navigation("BlockerUserProfile");
                });

            modelBuilder.Entity("Domain.Models.UserGoal", b =>
                {
                    b.HasOne("Domain.Models.Quest", "Quest")
                        .WithMany("UserGoal")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.UserProfile", "UserProfile")
                        .WithMany("UserGoals")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Quest");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Domain.Models.UserInventory", b =>
                {
                    b.HasOne("Domain.Models.ShopItem", "ShopItem")
                        .WithMany("UserInventories")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.UserProfile", "UserProfile")
                        .WithMany("InventoryItems")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Domain.Models.UserProfile", b =>
                {
                    b.HasOne("Domain.Models.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("Domain.Models.UserProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Domain.Models.UserProfile_Badge", b =>
                {
                    b.HasOne("Domain.Models.Badge", "Badge")
                        .WithMany("UserProfile_Badges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Models.UserProfile", "UserProfile")
                        .WithMany("UserProfile_Badges")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Domain.Models.WeeklyQuest_Day", b =>
                {
                    b.HasOne("Domain.Models.Quest", "Quest")
                        .WithMany("WeeklyQuest_Days")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.Badge", b =>
                {
                    b.Navigation("UserProfile_Badges");
                });

            modelBuilder.Entity("Domain.Models.Quest", b =>
                {
                    b.Navigation("MonthlyQuest_Days");

                    b.Navigation("QuestOccurrences");

                    b.Navigation("Quest_QuestLabels");

                    b.Navigation("SeasonalQuest_Season");

                    b.Navigation("Statistics");

                    b.Navigation("UserGoal");

                    b.Navigation("WeeklyQuest_Days");
                });

            modelBuilder.Entity("Domain.Models.QuestLabel", b =>
                {
                    b.Navigation("Quest_QuestLabels");
                });

            modelBuilder.Entity("Domain.Models.ShopItem", b =>
                {
                    b.Navigation("ActiveUserEffects");

                    b.Navigation("UserInventories");
                });

            modelBuilder.Entity("Domain.Models.UserProfile", b =>
                {
                    b.Navigation("ActiveUserEffects");

                    b.Navigation("FriendshipsAsUser1");

                    b.Navigation("FriendshipsAsUser2");

                    b.Navigation("InventoryItems");

                    b.Navigation("Labels");

                    b.Navigation("Notifications");

                    b.Navigation("Quests");

                    b.Navigation("ReceivedBlocks");

                    b.Navigation("ReceivedFriendInvitations");

                    b.Navigation("SentBlocks");

                    b.Navigation("SentFriendInvitations");

                    b.Navigation("UserGoals");

                    b.Navigation("UserProfile_Badges");
                });
#pragma warning restore 612, 618
        }
    }
}
